### ISSUE TITLE
TypeError: Object [object Object] has no method 'npmRequire'

### ISSUE THREAD

**Issue by athyuttamre** [ritstudentgovernment/accounts-saml2#3]
```
W20151211-20:21:43.993(-5)? (STDERR) /Users/athyuttamre/.meteor/packages/meteor-tool/.1.1.10.1tp5jln++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151211-20:21:43.993(-5)? (STDERR)                        throw(ex);
W20151211-20:21:43.993(-5)? (STDERR)                              ^
W20151211-20:21:43.997(-5)? (STDERR) TypeError: Object [object Object] has no method 'npmRequire'
W20151211-20:21:43.997(-5)? (STDERR)     at Package (packages/ritstudentgovernment_accounts-saml2/packages/ritstudentgovernment_accounts-saml2.js:93:1)
W20151211-20:21:43.997(-5)? (STDERR)     at Package (packages/ritstudentgovernment_accounts-saml2/packages/ritstudentgovernment_accounts-saml2.js:226:1)
W20151211-20:21:43.997(-5)? (STDERR)     at /Users/athyuttamre/Documents/Testbed/meteor/auth/.meteor/local/build/programs/server/packages/ritstudentgovernment_accounts-saml2.js:250:4
W20151211-20:21:43.997(-5)? (STDERR)     at /Users/athyuttamre/Documents/Testbed/meteor/auth/.meteor/local/build/programs/server/packages/ritstudentgovernment_accounts-saml2.js:257:3
W20151211-20:21:43.997(-5)? (STDERR)     at /Users/athyuttamre/Documents/Testbed/meteor/auth/.meteor/local/build/programs/server/boot.js:242:10
W20151211-20:21:43.998(-5)? (STDERR)     at Array.forEach (native)
W20151211-20:21:43.998(-5)? (STDERR)     at Function._.each._.forEach (/Users/athyuttamre/.meteor/packages/meteor-tool/.1.1.10.1tp5jln++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151211-20:21:43.998(-5)? (STDERR)     at /Users/athyuttamre/Documents/Testbed/meteor/auth/.meteor/local/build/programs/server/boot.js:137:5
```

I'm getting the error above on a brand new Meteor project, with only this package installed. I'm running Meteor v1.2. Any clue what's wrong?

**Comment by petermikitsh** [comment]
This project is no longer actively maintained. Maybe https://atmospherejs.com/natestrauser/accounts-saml or https://github.com/tvoglund/accounts-saml-shibboleth/ will do.

**Comment by athyuttamre** [comment]
Thanks, unfortunately none of the other SAML packages create accounts for users dynamically. They all seem to assume existing accounts.

**Comment by petermikitsh** [comment]
You could try forking this package and making the necessary modifications to fix it, if you need SAML authentication.

**Comment by athyuttamre** [comment]
I'll do my best, thank you!

**Comment by petermikitsh** [comment]
For sure! If you hit any roadblocks, feel free to reach out. My contact info (e-mail) is on my profile page.
